# Nightly performance test pipeline

trigger: none # No CI build

pr: # run on PRs only if perf tests were changed
  branches:
    include:
      - master
  paths:
    include:
      - test/perf/*

schedules:
- cron: "0 6 * * *" # Time is UTC
  displayName: Nightly Perf Test
  branches:
    include:
      - master
  always: true


jobs:
- template: templates/perf-tests-job-template.yml
  parameters:
    vmImage: 'vs2017-win2016'