parameters:
  name: 'Performance'
  vmImage: 'ubuntu-latest'
  pyVersions: [3.7]
  datasets: ["adult_uci", "compas"]
  predictors: ["rbm_svm", "decision_tree_classifier"]
  mitigators: ["GridSearch", "ExponentiatedGradient", "ThresholdOptimizer"]

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 10
    matrix:
      ${{ each pyVer in parameters.pyVersions }}:
        ${{ each dataset in parameters.datasets}}:
          ${{ each predictor in parameters.predictors}}:
            ${{ each mitigator in parameters.mitigators}}:
              ${{ pyVer }}:
                PyVer: ${{ pyVer }}
                dataset: ${{ dataset }}
                predictor: ${{ predictor }}
                mitigator: ${{ mitigator }}
  timeoutInMinutes: 120

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(PyVer)'
    inputs:
      versionSpec: '$(PyVer)' 
      addToPath: true

  - script: pip install -r requirements.txt
    displayName: 'Install required packages'

  - script: pip install azureml-sdk
    displayName: 'Install azureml-sdk'

  - script: python -m pytest -s test/perf --junitxml=./TEST--TEST.xml -o junit_suite_name="$(Agent.JobName)" --dataset $(dataset) --predictor $(predictor) --mitigator $(mitigator)
    displayName: 'Run Perf tests'
    env:
      SERVICE_PRINCIPAL_PASSWORD: $(fairlearnautomationspsecret)
      SERVICE_PRINCIPAL_ID: $(fairlearnautomationspid)
      TENANT_ID: $(fairlearnautomationsptenantid)
      SUBSCRIPTION_ID: cecafb73-04ae-4432-9f96-d96925d28058
      RESOURCE_GROUP_NAME: fairlearn-automation
      WORKSPACE_NAME: fairlearnperf
      WORKSPACE_LOCATION: canadacentral

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/TEST-*.xml'
    condition: succeededOrFailed()
