parameters:
  dependsOnStage: ''
  poolImage: ''
  deployToTest: true
  packageArtifactStem: 'Packages'
  versionArtifactStem: 'Version'
  versionFileStem: 'versionInfo'


stages:
- stage:
  - ${{ if eq(parameters.deployToTest}, 'true') }}:
    name: "Create_PyPI_Package_Test"
  - ${{ if eq(parameters.deployToTest}, 'false') }}:
    name: "Create_PyPI_Package_Prod"

  dependsOn:
  - ${{parameters.dependsOnStage}}

  variables:
  - template: variables-template.yml
    parameters:
      deployToTest: ${{parameters.deployToTest}}

  jobs:
  - job:
    pool:
      vmImage: ${{parameters.poolImage}}

    steps:
    - template: create-wheel-step-template.yml
      parameters:
        isTest: $(isTestDeployment)
        packageArtifactName: '${{parameters.packageArtifactStem}}$(nameSuffix)'
        versionArtifactName: '${{parameters.versionArtifactStem}}$(nameSuffix)'
        versionFilename: '${{parameters.versionFileStem}}$(nameSuffix)'