parameters:
  dependsOnStage: ''
  poolImage: ''
  targetType: 'Test'
  packageArtifactStem: 'Packages'
  versionArtifactStem: 'Version'
  versionFileStem: 'versionInfo'

stages:
- stage: 'Create_PyPI_Package_${{parameters.targetType}}'

  dependsOn:
  - ${{parameters.dependsOnStage}}

  jobs:
  - job:
    pool:
      vmImage: ${{parameters.poolImage}}

    steps:
    - template: create-wheel-step-template.yml
      parameters:
        targetType: ${{parameters.targetType}}
        packageArtifactName: '${{parameters.packageArtifactStem}}${{parameters.targetType}}'
        versionArtifactName: '${{parameters.versionArtifactStem}}${{parameters.targetType}}'
        versionFilename: '${{parameters.versionFileStem}}${{parameters.targetType}}'