parameters:
  poolImage: ''
  poolPythonVersion: 3.6
  targetType: 'Test'
  targetEnvironment: 'PyPI-Test Deployment'
  packageArtifactStem: 'Packages'
  versionArtifactStem: 'Version'
  versionFileStem: 'versionInfo'

stages:
- stage: 'Create_PyPI_Package_${{parameters.targetType}}'

  jobs:
  - job: 'Create_Package'
    pool:
      vmImage: ${{parameters.poolImage}}

    steps:
    - template: create-wheel-step-template.yml
      parameters:
        targetType: ${{parameters.targetType}}
        packageArtifactName: '${{parameters.packageArtifactStem}}${{parameters.targetType}}'
        versionArtifactName: '${{parameters.versionArtifactStem}}${{parameters.targetType}}'
        versionFilename: '${{parameters.versionFileStem}}${{parameters.targetType}}'


- stage: 'Upload_Package_To_PyPI_${{parameters.targetType}}'

  jobs:
  - deployment: 'PyPI_${{parameters.targetType}}'
    environment: ${{parameters.targetEnvironment}}
    pool:
      vmImage: ${{parameters.poolImage}}

    variables:
      packageDirectory: '${{parameters.packageArtifactStem}}${{parameters.targetType}}'
      ${{ if eq(parameters.targetType, 'Test') }}:
        pypiUrl: https://test.pypi.org/legacy/
      ${{ if eq(parameters.targetType, 'Prod') }}:
        pypiUrl: https://upload.pypi.org/legacy/

    strategy:
      runOnce:
       deploy:
        steps:
          - task: UsePythonVersion@0
            displayName: 'Use Python ${{parameters.poolPythonVersion}}'
            inputs:
              versionSpec: ${{parameters.poolPythonVersion}}
              addToPath: true

          - script: pip install twine
            displayName: 'Install twine'

          - script: ls -R $(Pipeline.Workspace)/$(PackageDirectory)
            displayName: "Files in $(Pipeline.Workspace)/$(PackageDirectory)"

          - script: echo "python twine upload --repository-url $(pypiUrl) $(Pipeline.Workspace)/$(PackageDirectory)/*"
            displayName: "Run twine for upload"


- stage: 'Validate_Package_from_PyPI_${{parameters.targetType}}'
  
  jobs:
  - template: unit-tests-pypi-job-template.yml
    parameters:
      name: Linux
      vmImage: 'ubuntu-16.04'
      pyVersions: [3.6, 3.7]
      targetType: ${{parameters.targetType}}
      versionFileArtifact: '${{parameters.versionArtifactStem}}${{parameters.targetType}}'
      versionFileName: '${{parameters.versionFileStem}}${{parameters.targetType}}'