variables:
  poolImage: "ubuntu-latest"
  poolPythonVersion: 3.6

trigger: none # No CI build

pr: none # Not for pull requests

stages:
- template: pypi-deployment-stages-template.yml
  parameters:
    poolImage: $(PoolImage)
    targetType: 'Test'
    kvSubscription: fairlearn-pipeline-learning # This is actually the name of the service connection from the Project Settings page
    kvVaultName: fairlearndeploy
    kvUsername: 'usernametest'
    kvPassword: 'passwordtest'