parameters:
  name: ''
  vmImage: ''
  pyVersions: [3.5, 3.6, 3.7]
  requirementsFile: 'requirements.txt'
  gitUrl: https://github.com/fairlearn/fairlearn.git
  gitCheckoutTarget: $(Build.SourceVersion) # This is the safe default, which should select the code version for the current pipeline
  usePyPITest: true
  pipVersionfairlearn:
  prerequisiteJob:
  versionFileArtifact:
  versionFileName:

jobs:
- job: ${{ parameters.name }}
  dependsOn: ${{parameters.prerequisiteJob}}
  pool:
    vmImage: ${{ parameters.vmImage }}

  variables:
    ${{ if eq(parameters.usePyPITest, 'true') }}:
      pypiUrl: https://test.pypi.org/simple/
    ${{ if eq(parameters.usePyPITest, 'false') }}:
      pypiUrl: https://pypi.org/simple/
    fairlearnVersionForpip: ${{parameters.pipVersionfairlearn}}
        

  strategy:
    maxParallel: 2
    matrix:
      ${{ each pyVer in parameters.pyVersions }}:
        ${{ pyVer }}:
          PyVer: ${{ pyVer }}

  steps:
  - ${{ if eq(parameters.pipVersionfairlearn, '') }}:
    - template: fetch-version-from-artifacts-steps-template.yml
      parameters:
        artifactName: ${{parameters.versionFileArtifact}}
        artifactFile: ${{parameters.versionFileName}}
        targetVariable: fairlearnVersionForpip

  - task: UsePythonVersion@0
    displayName: 'Use Python $(PyVer)'
    inputs:
      versionSpec: '$(PyVer)' 
      addToPath: true

  - task: PowerShell@2
    name: PrepareGit
    displayName: "Clone from GitHub and checkout ${{parameters.gitCheckoutTarget}}"
    inputs:
      filePath: scripts/prepare-git-pypi-test.ps1
      arguments: "-gitUrl ${{parameters.gitUrl}} -baseDir $(Agent.TempDirectory) -targetVariable ClonedRepoDir -gitCheckout ${{parameters.gitCheckoutTarget}}"
      pwsh: true

  - script: pip install -r ${{ parameters.requirementsFile }}
    displayName: 'Install required packages specified in ${{ parameters.requirementsFile }}'
    workingDirectory: $(ClonedRepoDir)

  - script: pip install --index-url $(pypiUrl) fairlearn==$(fairlearnVersionForpip)
    displayName: "Install fairlearn version $(fairlearnVersionForpip) from $(pypiUrl)"

    # DO NOT CHECK IN FOLLOWING LINE WITHOUT FIXING TEST PATH
  - script: python -m pytest test/unit/metrics --ignore=test/perf --junitxml=./TEST--TEST.xml -o junit_suite_name="$(Agent.JobName) git=${{parameters.gitcheckoutTarget}} test=${{parameters.usePyPITest}} pipVersion=$(fairlearnVersionForpip)"
    displayName: 'Run tests'
    workingDirectory: $(ClonedRepoDir)

  
  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/TEST-*.xml'
    inputs:
      searchFolder: $(ClonedRepoDir)
    condition: succeededOrFailed()
