repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
        exclude: .github/conda/meta.yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
# Need to keep black version consistent in
# requirements-dev.txt
# linting.yml
# .pre-commit-config.yaml
    rev: 23.9.1
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        types: [file, python]
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
