trigger: none

pr: none

schedules:
- cron: "0 6 * * *" # Time is UTC
  displayName: Daily midnight build
  branches:
    include:
      - master
      - dev
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6' 
    addToPath: true

- script: pip install -r requirements.txt
  displayName: 'Install required packages'

- script: python -m pytest notebooks/ --nbval --junitxml=./TEST-TEST.xml
  displayName: 'Run notebooks as tests'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed()
