parameters:
  name: ''
  vmImage: ''
  pyVersions: [Py-35, Py-36]

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 2
    matrix:
      ${{ each pyVer in parameters.pyVersions }}
        ${{ pyVer }}:
          PyVer: ${{ pyVer }}

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(PyVer)'
    inputs:
      versionSpec: '$(PyVer)' 
      addToPath: true

  - script: pip install -r requirements.txt
    displayName: 'Install required packages'

  - script: flake8 .
    displayName: "Run flake8"

  - script: python -m pytest test/ --junitxml=./TEST--TEST.xml -o junit_suite_name="$(Agent.JobName)"
    displayName: 'Run tests'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/TEST-*.xml'
    condition: succeededOrFailed()