trigger: none # No CI build

schedules:
- cron: "0 4 * * *" # Time is UTC
  displayName: Daily build
  branches:
    include:
      - master
      - dev
  always: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
- template: all-tests-job-template.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-16.04'
    pyVersions: [3.5]

- template: all-tests-job-template.yml
  parameters:
    name: Windows
    vmImage:  'vs2017-win2016'
    pyVersions: [3.6]
    
- template: all-tests-job-template.yml
  parameters:
    name: MacOS
    vmImage:  'macOS-10.13'
    pyVersions: [ 3.7] 
