trigger: none # No CI build

schedules:
- cron: "0 4 * * *" # Time is UTC
  displayName: Daily build
  branches:
    include:
      - master
      - dev
  always: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: PR_Gate
  strategy:
    maxParallel: 2
    matrix:
      Py35:
        PyVer: 3.5
      Py36:
        PyVer: 3.6


  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(PyVer)' 
      addToPath: true

  - script: pip install -r requirements.txt
    displayName: 'Install required packages'

  - script: flake8 .
    displayName: "Run flake8"

  - script: python -m pytest test/ --junitxml=./TEST-TEST.xml 
    displayName: 'Run tests'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/TEST-*.xml'
    condition: succeededOrFailed()
