name: fairlearn-xgboost
channels:
- defaults
- conda-forge
dependencies:
- python==3.11
- pip>=19.1.1
- pytest
- pytest-cov
- xgboost>=1.7.0
- pandas

# Note xgboost not available for Windows on conda-forge
# See
# https://stackoverflow.com/questions/62241123/unable-to-install-xgboost-on-conda-forge