name: fairlearn-xgboost
channels:
- conda-forge
dependencies:
- python>=3.10
- pip>=19.1.1
- pytest
- pytest-cov
- xgboost>=1.7.0,<2.1.5
- pandas
- scipy<1.16.0

# Note xgboost not available for Windows on conda-forge
# See
# https://stackoverflow.com/questions/62241123/unable-to-install-xgboost-on-conda-forge
