name: fairlearn-lightgbm
channels:
- defaults
- conda-forge
dependencies:
- python==3.10
- pip>=19.1.1
- numpy
- pandas
- pytest
- pytest-cov
- scikit-learn
- lightgbm<4.0.0  # 4.0.0 is incompatible with latest numpy https://github.com/microsoft/LightGBM/issues/5990