name: fairlearn-pytorch
channels:
- conda-forge
dependencies:
- python>=3.10
- pip>=19.1.1
- pytest
- pytest-cov
- pytorch-cpu
- pip:
   - skorch>=0.12.1

# Note pytorch will not install cuda. If you do not want that, please
# use conda install pytorch -c pytorch
# See
# https://pytorch.org/get-started/locally/
