name: fairlearn-pytorch
channels:
- conda-forge
dependencies:
- python>=3.10
- pip>=19.1.1
- pytest
- pytest-cov
# Remove constraints when https://github.com/skorch-dev/skorch/issues/1071 is fixed
- pytorch<2.4
- pytorch-cpu<2.4
- skorch

# Note pytorch will not install cuda. If you do not want that, please
# use conda install pytorch -c pytorch
# See
# https://pytorch.org/get-started/locally/
