# template for building the widget/fairlearn dashboard

parameters:
  name: 'BuildWidget'
  vmImage: 'ubuntu-latest'
  pyVersion: 3.6

jobs:
- job:  ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - script: ls
    displayName: "find yarn path"
  
  - script: ls /
    displayName: "find yarn path /"
  
  - script: ls /etc
    displayName: "find yarn path /etc"
  
  - script: ls /bin
    displayName: "find yarn path /bin"

  - task: PowerShell@2
    displayName: 'Build widget'
    inputs:
      filePath: python scripts/build_widget.py --assert-no-changes --yarn-path yarn
      pwsh: true