# Step templates to create the wheels and file specifying the current version
# Note that this uses the DEV_VERSION variable

parameters:
  pyVer: 3.6
  targetType: ''
  versionFilename: ''
  packageArtifactName: ''
  versionArtifactName: ''
  freezeArtifactStem: 
  freezeFile:

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python ${{parameters.pyVer}}'
  inputs:
    versionSpec: ${{parameters.pyVer}}
    addToPath: true

- template: python-infra-upgrade-steps-template.yml

- script: pip install setuptools wheel 
  displayName: 'Install setuptools'

- script: pip install -r requirements.txt
  displayName: "Install fairlearn requirements"

- template: pip-freeze-to-artifact-steps-template.yml
  parameters:
    freezeArtifact: '${{parameters.freezeArtifactStem}}CreateWheel'
    freezeFile: ${{parameters.FreezeFile}}

- script: python ./scripts/build_widget.py --assert-no-changes --yarn-path /usr/bin/yarn
  displayName: 'Build widget'

- script: python ./scripts/build_wheels.py --target-type ${{parameters.targetType}} --version-filename ${{parameters.versionFilename}} --dev-version $(DEV_VERSION)
  displayName: 'Build wheels'

- task: PublishPipelineArtifact@1
  displayName: "Publish wheels"
  inputs:
    path: $(System.DefaultWorkingDirectory)/dist
    artifact: '${{parameters.packageArtifactName}}'

- task: PublishPipelineArtifact@1
  displayName: "Publish version information file"
  inputs:
    path: '$(System.DefaultWorkingDirectory)/${{parameters.versionFilename}}'
    artifact: '${{parameters.versionArtifactName}}'