# Template to install fairlearn from designated location

parameters:
  installationType: 'None'
  pypiUrl:
  versionArtifactName:
  versionArtifactFile:
  pipVersionVariable: 'pipVersionVar'

steps:
# Validation of installationType
# Something is strange with template condition vs task condition
- ${{ if notIn(parameters.installationType, 'None', 'Editable', 'PyPI') }}:
  - script: exit 1
    displayName: "Bad installationType: ${{parameters.installationType}}"
    condition: notIn('${{parameters.installationType}}', 'None', 'Editable', 'PyPI')

# ==============================================================
# Install editable
- ${{ if eq(parameters.installationType, 'Editable') }}:
  - script: pip install -e .
    displayName: "Install fairlearn in editable mode"

# ===============================================================
# Install from a wheel package
- ${{ if in(parameters.installationType, 'PyPI', 'WheelArtifact') }}:
  # Clear out the checked out code
  - task: DeleteFiles@1
    inputs:
      contents: |
        fairlearn
        devops
        docs
        *.md

  - script: ls -p
    displayName: "List after deletion"

  # Install from PyPI
  - ${{ if eq(parameters.installationType, 'PyPI') }}:
    - task: DownloadPipelineArtifact@2
      displayName: "Download version Artifact ${{parameters.versionArtifactName}}"
      inputs:
        artifact: ${{parameters.versionArtifactName}}
        path: $(Build.SourcesDirectory)

    - script: ls -p
      displayName: "Show sources directory"

    - task: PowerShell@2
      displayName: 'Read version Artifact and set pipeline variable from file contents'
      inputs:
        filePath: scripts/set-variable-from-file.ps1
        arguments: "-baseDir $(Pipeline.Workspace) -subDir . -fileName ${{parameters.versionArtifactFile}} -targetVariable ${{parameters.pipVersionVariable}}"
        pwsh: true
    
    - script: pip install --index-url ${{parameters.pypiUrl}} fairlearn==$(${{parameters.pipVersionVariable}})
      displayName: "Install fairlearn with pip"
    