parameters:
- name: stageName
  type: string
- name: previousStages
  type: string
  default: UploadWheel
- name:  poolImage
  type: string
  default: 'ubuntu-latest'
- name: poolPythonVersion
  type: number
  default: 3.6
- name: releaseType
  type: string
  default: Test
  values:
  - Test
  - Prod
  - Production
- name: versionArtifactName
  type: string
- name: versionFileName
  type: string
- name: freezeArtifactStem
  type: string
- name: freezeFileStem
  type: string


stages:
- stage: ${{parameters.stageName}}
  displayName: Test from PyPI
  dependsOn: ${{parameters.previousStages}}
  pool:
    vmImage: ${{parameters.poolImage}}

  jobs:
  - template: all-tests-job-template.yml
    parameters:
      platforms:  { Linux: ubuntu-latest, Windows: vs2017-win2016 }
      pyVersions: [3.5, 3.6, 3.7, 3.8]
      freezeArtifactStem: ${{parameters.freezeArtifactStem}}
      freezeFileStem: ${{parameters.freezeFileStem}}
      installationType: 'PyPI'
      targetType: ${{parameters.releaseType}}
      versionArtifactName: '${{parameters.versionArtifactName}}'
      versionArtifactFile: '${{parameters.versionFileName}}'