parameters:
  pyVer:
  requirementsFile:
  pinRequirements:

steps:
- ${{ each reqFile in [ 'requirements.txt', 'requirements-customplots.txt', 'requirements-dev.txt'] }}:
  - script: python scripts/requirements_pin.py --input ${{reqFile}} --output '${{reqFile}}-fixed' --loglevel INFO
    displayName: "Pin ${{reqFile}}"
    condition: eq('${{parameters.pinRequirements}}', True)

  - script: pip install -r ${{reqFile}}-fixed
    displayName: "Install ${{reqFile}}-fixed"
    condition: eq('${{parameters.pinRequirements}}', True)

  - script: pip install -r ${{reqFile}}
    displayName: "Install ${{reqFile}}"
    condition: ne('${{parameters.pinRequirements}}', True)
