name: Test with Other ML Packages


on: [push, pull_request]

concurrency: 
  # this ensures after each commit the old jobs are cancelled and the new ones
  # run instead.
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  baseDir: test_othermlpackages
  condaEnv: test-conda-env
  poolImage: ubuntu-latest
  pythonVersion: 3.8

jobs:
  other-ml:
    strategy:
      matrix:
        mlpackage: [ lightgbm, xgboost, tensorflow, pytorch]
    runs-on: ubuntu-latest
    env:
      CONDA_FILENAME: "${{ format('{0}/conda-{1}.yaml', env.baseDir, matrix.mlpackage) }}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PythonVersion }}
      - run: conda env create --name ${{env.condaEnv}} --file=${{env.CONDA_FILENAME}}