name: linting

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python:
        required: true
        type: string

jobs:
  ruff:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
  ruff-format:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/ruff-action@v4
        with:
          version: 0.15.20
          args: "format --check --diff"
  build-wheel:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install build
      run: |
        pip install --upgrade pip
        pip install --upgrade build
    - name: Build sdist and wheel
      run: python -m build
