name: linting

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python:
        required: true
        type: string

jobs:
  linting-flake8:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python }}
      - run: pip install -r requirements-dev.txt
      - run: flake8 .
  linting-black:
    # Need to keep black version consistent in
    # requirements-dev.txt
    # linting.yml
    # .pre-commit-config.yaml
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@23.9.1
