env:
  FreezeArtifactStem: 'freeze'
  FreezeFileStem: 'requirements-freeze'

on:
  pull_request:
    branches:
      - main
      - 'release/*''

pool:
  vmImage: 'ubuntu-latest'

jobs:
  linux_job:
    runs-on: ubuntu-latest
    name: all-tests-linux
    steps:
      - uses: ./.github/actions/all-tests-job-template
        with:
          platforms:  { Linux: ubuntu-latest }
          installationType: 'PipLocal'
          pyVersions: [3.9]
          freezeArtifactStem: ${{ env.FreezeArtifactStem }}
          freezeFileStem: ${{ env.FreezeFileStem }}
  
  windows_job:
    runs-on: windows-latest
    name: all-tests-windows
    steps:
      - uses: ./.github/actions/all-tests-job-template
        with:
          platforms:  { Linux: windows-latest }
          installationType: 'PipLocal'
          pyVersions: [3.9]
          freezeArtifactStem: ${{ env.FreezeArtifactStem }}
          freezeFileStem: ${{ env.FreezeFileStem }}

  macos_job:
    runs-on: macos-latest
    name: all-tests-macos
    steps:
      - uses: ./.github/actions/all-tests-job-template
        with:
          platforms:  { Linux: macos-latest }
          testRunTypes: ['Unit']
          installationType: 'None'
          pyVersions: ["3.8", "3.10"]
          freezeArtifactStem: ${{ env.FreezeArtifactStem }}
          freezeFileStem: ${{ env.FreezeFileStem }}
    
# - template: templates/limited-installation-job-template.yml
