name: test-all-deps

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python:
        required: true
        type: string
      codeCovPython:
        required: true
        type: string
        default: "3.12"


jobs:
  all-deps:
    runs-on: ${{ inputs.os }}
    env:
      MPLBACKEND: Agg
      UV_SYSTEM_PYTHON: 1

    steps:
      - uses: actions/checkout@v4

      - name: Get commit date
        id: get_date
        shell: bash
        run: |
          COMMIT_DATE=$(git show -s --format=%ct ${{ github.sha }})
          CURRENT_DATE=$(date +%s)
          AGE=$((CURRENT_DATE - COMMIT_DATE))
          echo "AGE=$AGE" >> $GITHUB_OUTPUT
          echo "AGE in seconds: $AGE"

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv run python scripts/install_requirements.py

      - name: Install fairlearn and extras
        run: |
          uv pip install .
          uv pip install matplotlib

      - name: Run tests
        run: >
          uv run pytest --mpl
          --mpl-baseline-path='${{ github.workspace }}/test/unit/plot_snapshots'
          --ignore=test/install --cov=fairlearn --cov-report=xml -vl test/

      - name: Upload coverage reports to Codecov with GitHub Action
        if: ${{ (inputs.codeCovPython == inputs.python) && (steps.get_date.outputs.AGE < 172800) }} # 172800 = 48 * 3600
        uses: codecov/codecov-action@v4.2.0
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true
