name: test-minimal-deps

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python:
        required: true
        type: string
      codeCovPython:
        required: true
        type: string
        default: "3.11"

jobs:
  minimal-deps:
    # This job installs minimal dependencies and runs tests for the minimal
    # dependency cases. This also covers the case where matplotlib is not
    # installed, i.e., fairlearn without extras.
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Get commit date
        id: get_date
        run: |
          COMMIT_DATE=$(git show -s --format=%ct ${{ github.sha }})
          CURRENT_DATE=$(date +%s)
          AGE=$((CURRENT_DATE - COMMIT_DATE))
          echo "::set-output name=age::$AGE"
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python }}
      - run: pip install .
      - run: pip install pytest pytest-cov
      - run: pytest --cov=fairlearn --cov-report=xml test/install
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: ${{ (inputs.codeCovPython == inputs.python) && (steps.get_date.outputs.age < 172800) }}
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
