name: test-minimal-deps

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python:
        required: true
        type: string
      codeCovPython:
        required: true
        type: string
        default: "3.11"

jobs:
  minimal-deps:
    # This job installs minimal dependencies and runs tests for the minimal
    # dependency cases. This also covers the case where matplotlib is not
    # installed, i.e., fairlearn without extras.
    # CodeCov limits us to 150 uploads per commit id, so have an extra check so
    # we only upload results if the current commit is under 48 hours old
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Get commit date
        id: get_date
        shell: bash
        run: |
          COMMIT_DATE=$(git show -s --format=%ct ${{ github.sha }})
          CURRENT_DATE=$(date +%s)
          AGE=$((CURRENT_DATE - COMMIT_DATE))
          echo "AGE=$AGE" >> $GITHUB_OUTPUT
          echo "AGE in seconds: $AGE"
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python }}
      - run: pip install .
      - run: pip install pytest pytest-cov
      - run: pytest --cov=fairlearn --cov-report=xml test/install
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4.2.0
        env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
